classdef CalibrationPersistence < io.mpa.Persistence

	enumeration

		MEASUREMENTS([...
			CalibrationSchema.INTENSITY_MEASUREMENT, ...
			CalibrationSchema.LINEARITY_MEASUREMENT, ...
			CalibrationSchema.NDF_MEASUREMENT, ...
			CalibrationSchema.SPECTRAL_MEASUREMENT, ...
		])
	end
end